name: Continous Integration and Deployment
on:
  push:
    Branches: 
      - main 
env: 
    VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID }}
jobs: 
    built: 
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps: 
            - name: install Node.js 22.x
              uses: actions/setup-node@v2
              woth: 
                node-version: 22.x
            - name: install dependencies 
              run: yarn install
            - name: Build
              run: yarn build
    Deploy:
      needs: Build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps: 
        -uses: actions/checkout@v2
        -name: install Node.js 22.x
        uses: actions/setup-node@v2
        with: 
          node-version: 22.x
        -name: install vercel CLI
        run: yarn global add vercel
        -name: Pull Vercel Environment Variables 
        run: vercel pull --yes --token= ${{secrets_VERCEL_TIKEN}} 
        -name: Deploy to Vercel
        run: vercel deply --no-wait --token= ${{secrets_VERCEL_TIKEN}}            