name: Integration and Deploy
on:
  push:
    branches:
      - main
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Node.js 22.x
        uses: actions/setup-node@v2
        with: 
          node-version: 22.x

      - name: vercel CLI
        run: npm install -g vercel

      - name: Vercel Environment
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN }}         